version: "3"
services:
  mysql-1:
    image: mysql:5
    container_name: 'mysql-container-01'
    restart: 'always'
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test01test01
    volumes:
      - ./configs/mysql:/etc/mysql/conf.d
  memcached-1:
    image: memcached:latest
    container_name: 'memcached-container-01'
    restart: 'always'
    ports:
      - "9000:9000"
